#!/bin/bash
kubectl config set-cluster vagrant-multi-cluster --server=https://172.19.0.101:443 --certificate-authority=./ssl/ca.pem
kubectl config set-credentials vagrant-multi-admin --certificate-authority=./ssl/ca.pem --client-key=./ssl/admin-key.pem --client-certificate=./ssl/admin.pem
kubectl config set-context vagrant-multi --cluster=vagrant-multi-cluster --user=vagrant-multi-admin
kubectl config use-context vagrant-multi
